#!/usr/bin/env bash
#
# One-shot Docker deployment for wearorder-api on Debian 12.
#
# Run as root or with sudo from the `backend/` directory:
#     cd /srv/wearorder/backend && sudo bash deploy/docker-install.sh
#
# Idempotent. Re-running upgrades the image and restarts the container
# without losing the SQLite database (it lives in a named volume).

set -euo pipefail

# Color helpers — only when stdout is a TTY.
if [[ -t 1 ]]; then
    GREEN=$'\e[32m'; YELLOW=$'\e[33m'; RED=$'\e[31m'; BOLD=$'\e[1m'; RESET=$'\e[0m'
else
    GREEN=""; YELLOW=""; RED=""; BOLD=""; RESET=""
fi

log()  { echo "${GREEN}==>${RESET} $*"; }
warn() { echo "${YELLOW}!! ${RESET} $*"; }
fail() { echo "${RED}X${RESET} $*" >&2; exit 1; }

if [[ $EUID -ne 0 ]]; then
    fail "Run as root (sudo bash $0)"
fi

# Always run from the directory containing the compose file, regardless
# of where the script was invoked from.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPOSE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$COMPOSE_DIR"

if [[ ! -f docker-compose.yml ]]; then
    fail "docker-compose.yml not found in $(pwd) — run this from the backend/ directory"
fi

# ---------- Phase 1: Docker engine ----------

log "Phase 1/5 — checking Docker engine"
if ! command -v docker &>/dev/null; then
    log "Installing Docker via official convenience script"
    # get.docker.com handles Debian repo setup + apt install in one shot.
    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker
else
    log "Docker already installed: $(docker --version)"
fi

# Compose v2 ships as a CLI plugin alongside Docker. Some older Debian
# images miss it; ensure it's present.
if ! docker compose version &>/dev/null; then
    log "Installing docker compose plugin"
    apt-get update -qq
    apt-get install -y docker-compose-plugin
fi
log "compose: $(docker compose version | head -1)"

# ---------- Phase 2: firewall ----------

log "Phase 2/5 — opening firewall ports 22 + 80"
if command -v ufw &>/dev/null; then
    ufw allow 22/tcp >/dev/null
    ufw allow 80/tcp >/dev/null
    yes | ufw enable >/dev/null 2>&1 || true
    log "ufw status:"
    ufw status verbose | sed 's/^/    /'
else
    warn "ufw not installed — make sure Tencent Cloud security group allows 22 + 80"
fi

# ---------- Phase 3: secrets ----------

log "Phase 3/5 — preparing .env (secrets)"
ENV_FILE="$COMPOSE_DIR/.env"
if [[ -f "$ENV_FILE" ]]; then
    log ".env already exists, leaving alone (delete it manually if you want a fresh secret)"
else
    SESSION_SECRET="$(openssl rand -hex 32)"
    cat > "$ENV_FILE" <<EOF
# Generated by docker-install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file private (chmod 600). Anyone with this secret can
# forge admin sessions.
SESSION_SECRET=${SESSION_SECRET}

# Override admin username if you want something less guessable.
# ADMIN_USERNAME=admin

# Per-device limits (defaults: 30/day, 5/min).
# RATE_LIMIT_PER_DAY=30
# BURST_LIMIT_PER_MINUTE=5
EOF
    chmod 600 "$ENV_FILE"
    log "Generated fresh SESSION_SECRET (saved to $ENV_FILE, mode 600)"
fi

# ---------- Phase 4: build + start ----------

log "Phase 4/5 — building image and starting container"
docker compose build --pull
docker compose up -d

# ---------- Phase 5: wait for healthcheck ----------

log "Phase 5/5 — waiting for /healthz to come up"
HEALTHY=0
for i in $(seq 1 30); do
    if curl -fsS --max-time 2 http://127.0.0.1/healthz >/dev/null 2>&1; then
        HEALTHY=1
        break
    fi
    sleep 1
done

if [[ $HEALTHY -eq 0 ]]; then
    warn "Service didn't pass healthcheck within 30s. Recent logs:"
    docker compose logs --tail=80 wearorder-api
    fail "Aborting — fix the issue and re-run this script."
fi

log "Service is healthy"
echo

# ---------- Done. Print bootstrap info ----------

PUBLIC_IP="$(curl -fsS --max-time 3 https://api.ipify.org 2>/dev/null \
            || curl -fsS --max-time 3 https://ifconfig.me 2>/dev/null \
            || echo "<your-server-ip>")"

echo "${BOLD}=========================================================${RESET}"
echo "${BOLD}  wearorder-api is running.${RESET}"
echo "${BOLD}=========================================================${RESET}"
echo
echo "  Admin login URL:  http://${PUBLIC_IP}/admin/login"
echo "  Public health:    http://${PUBLIC_IP}/healthz"
echo
echo "${YELLOW}  Admin bootstrap password (look for the box below):${RESET}"
echo
docker compose logs wearorder-api 2>&1 \
  | grep -B1 -A4 "Admin bootstrap" \
  | tail -8 \
  | sed 's/^/    /'
echo
echo "${YELLOW}  Save the password above into your password manager,${RESET}"
echo "${YELLOW}  then login and change it via Admin → Home → 修改密码.${RESET}"
echo
echo "  Useful commands:"
echo "    docker compose logs -f wearorder-api    # tail logs"
echo "    docker compose restart wearorder-api    # restart"
echo "    docker compose down                     # stop"
echo "    docker compose up -d --build            # rebuild and restart"
echo
echo "  Backup database:"
echo "    docker run --rm -v wearorder_wearorder-data:/data -v \$(pwd):/backup alpine \\"
echo "        cp /data/wearorder.db /backup/wearorder-\$(date +%F).db"
echo
